# Generated by Django 4.0.7 on 2023-03-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notifications_recipient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='link',
        ),
        migrations.AddField(
            model_name='notifications',
            name='link_id',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
