# Generated by Django 4.0.7 on 2023-03-21 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_friendnotifications_accepted_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendnotifications',
            name='friend_request_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
