# Generated by Django 4.0.7 on 2023-06-03 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_alter_friendnotifications_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagenotifications',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
