# Generated by Django 4.0.7 on 2023-03-12 09:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('privatechat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatechat',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='Users currently in the chat', related_name='chatrooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
