# Generated by Django 4.0.7 on 2023-03-23 20:39

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('privatechat', '0003_privatechat_unread_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatemessages',
            name='message',
            field=fernet_fields.fields.EncryptedTextField(),
        ),
    ]
