# Generated by Django 4.0.7 on 2023-03-11 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicchat', '0002_privatemessages_privatechat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatemessages',
            name='room',
        ),
        migrations.RemoveField(
            model_name='privatemessages',
            name='user',
        ),
        migrations.DeleteModel(
            name='PrivateChat',
        ),
        migrations.DeleteModel(
            name='PrivateMessages',
        ),
    ]
