# Generated by Django 4.0.7 on 2023-06-03 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicchat', '0004_publicmessages_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicmessages',
            name='language',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
