# Generated by Django 4.0.7 on 2023-02-11 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_accountinfo_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinfo',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_info_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accountinfo',
            name='summary',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
