# Generated by Django 4.0.7 on 2023-02-11 20:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_accountinfo_owner_alter_accountinfo_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinfo',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(2, 'Name must be more than two characters.')]),
        ),
        migrations.AlterField(
            model_name='accountinfo',
            name='summary',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
