# Generated by Django 4.0.7 on 2023-02-16 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_accountinfo_name_alter_accountinfo_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinfo',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to=settings.AUTH_USER_MODEL),
        ),
    ]
