# Generated by Django 4.0.7 on 2023-03-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_accountinfo_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
