# Generated by Django 4.0.7 on 2023-04-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_account_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='online_status',
            field=models.CharField(default='offline', max_length=15),
        ),
    ]
