# Generated by Django 4.0.7 on 2023-07-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_account_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
