# Generated by Django 4.0.7 on 2023-08-12 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_account_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='online',
        ),
    ]
